export const SKILLS_BY_FIELD: Record<string, string[]> = {
  "Full Stack": [
    "React",
    "Node.js",
    "TypeScript",
    "PostgreSQL",
    "REST APIs",
    "Docker",
    "Next.js",
    "GraphQL",
    "JavaScript",
    "Python",
    "MongoDB",
    "Redis",
    "AWS",
    "CI/CD",
    "Testing",
    "System design",
    "Prisma",
    "Tailwind CSS",
    "Express",
    "NestJS",
    "Git",
  ],
  "Digital Project Manager": [
    "Agile",
    "Scrum",
    "Jira",
    "Stakeholder management",
    "Roadmapping",
    "Budget management",
    "Risk management",
    "Kanban",
    "Confluence",
    "OKRs",
    "Sprint planning",
    "Delivery management",
    "Cross-functional leadership",
    "Product sense",
    "Reporting",
    "Notion",
    "JavaScript",
    "TypeScript",
    "Python",
    "SQL",
    "HTML/CSS",
    "APIs",
  ],
  "Networking Engineer": [
    "TCP/IP",
    "Cisco",
    "Routing & Switching",
    "Firewalls",
    "VPN",
    "Network security",
    "SD-WAN",
    "Juniper",
    "BGP",
    "OSPF",
    "Wi-Fi design",
    "Load balancers",
    "DNS",
    "DHCP",
    "Network monitoring",
    "Wireless",
  ],
  "Marketing Manager": [
    "Brand strategy",
    "Campaign management",
    "Content strategy",
    "Analytics",
    "Budget management",
    "Team leadership",
    "SEO",
    "SEM",
    "Go-to-market",
    "Positioning",
    "Email marketing",
    "Marketing ops",
    "A/B testing",
    "Lifecycle marketing",
    "CRM",
  ],
  "Hardware Engineer": [
    "Circuit design",
    "PCB layout",
    "Embedded systems",
    "Signal integrity",
    "Soldering",
    "Oscilloscope debugging",
    "FPGA",
    "Microcontrollers",
    "Power electronics",
    "EMC/EMI",
    "Schematic capture",
    "Bring-up",
    "Firmware basics",
  ],
  "PCB Design": [
    "Altium Designer",
    "KiCad",
    "Schematic capture",
    "Layout routing",
    "DFM",
    "Signal integrity",
    "OrCAD",
    "High-speed design",
    "Gerber files",
    "BOM management",
    "Multi-layer boards",
    "Impedance control",
  ],
  "QA Automation": [
    "Selenium",
    "Playwright",
    "Cypress",
    "CI/CD",
    "Test frameworks",
    "API testing",
    "Performance testing",
    "Jest",
    "Pytest",
    "TestRail",
    "Mobile automation",
    "Load testing",
    "Quality strategy",
    "Regression testing",
  ],
  "PPC Manager": [
    "Google Ads",
    "Meta Ads",
    "Campaign optimization",
    "A/B testing",
    "Budget management",
    "Analytics",
    "LinkedIn Ads",
    "Conversion tracking",
    "Remarketing",
    "Keyword research",
    "Landing page CRO",
    "Looker Studio",
  ],
  "Social Media Manager": [
    "Content creation",
    "Community management",
    "Social analytics",
    "Paid social",
    "Influencer marketing",
    "Copywriting",
    "Content calendar",
    "Instagram",
    "TikTok",
    "LinkedIn",
    "Creative briefs",
    "Social listening",
  ],
  "Cyber Security": [
    "Penetration testing",
    "SIEM",
    "Incident response",
    "Network security",
    "Threat intelligence",
    "Compliance",
    "SOC",
    "IAM",
    "Cloud security",
    "Vulnerability management",
    "Zero trust",
    "Security architecture",
    "Risk assessment",
  ],
  "DevOps": [
    "Kubernetes",
    "Docker",
    "CI/CD",
    "Terraform",
    "AWS/GCP/Azure",
    "Monitoring",
    "Linux administration",
    "Helm",
    "GitHub Actions",
    "Observability",
    "SRE practices",
    "Infrastructure as code",
    "Ansible",
    "Prometheus",
  ],
  "Project Manager (Systems/Software)": [
    "Agile",
    "Scrum",
    "Technical roadmapping",
    "Cross-functional coordination",
    "Risk management",
    "Release planning",
    "Dependency management",
    "Budget tracking",
    "Vendor management",
    "Status reporting",
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C#",
    "SQL",
    "Go",
    "Node.js",
    "React",
    "APIs",
    "Git",
    "Jira",
  ],
  "Architect (Software)": [
    "System design",
    "Microservices",
    "Cloud architecture",
    "API design",
    "Scalability",
    "Technical leadership",
    "Event-driven architecture",
    "Data modeling",
    "Security by design",
    "Performance",
    "Domain-driven design",
    "Tradeoff analysis",
  ],
  "Chemical Engineer": [
    "Process design",
    "Chemical safety",
    "Reactor design",
    "Quality control",
    "Regulatory compliance",
    "Process simulation",
    "HAZOP",
    "Scale-up",
    "Mass & energy balance",
    "Lab to plant",
  ],
  "Biochemistry Engineer": [
    "Lab techniques",
    "Protein analysis",
    "Fermentation",
    "Quality control",
    "Regulatory compliance",
    "Cell culture",
    "HPLC",
    "Assay development",
    "Bioprocess",
    "Documentation",
  ],
  Technologist: [
    "Process optimization",
    "Quality assurance",
    "Lab equipment",
    "Documentation",
    "Regulatory standards",
  ],
  "Mechanical Engineer": [
    "CAD",
    "SolidWorks",
    "AutoCAD",
    "Manufacturing processes",
    "Materials science",
    "Prototyping",
    "FEA",
    "GD&T",
    "3D printing",
    "Tolerance analysis",
    "Product design",
    "DFM",
  ],
  Pharma: [
    "GMP",
    "Regulatory affairs",
    "Clinical trials",
    "Quality assurance",
    "Validation",
    "Documentation",
  ],
  "Architecture (Building)": [
    "AutoCAD",
    "Revit",
    "Building codes",
    "Construction management",
    "Structural design",
    "SketchUp",
    "BIM",
    "Design development",
    "Site coordination",
    "Sustainability",
  ],
  "Civil/Building Engineer": [
    "Structural analysis",
    "AutoCAD",
    "Site supervision",
    "Building codes",
    "Project management",
    "Quantity surveying",
    "Concrete design",
    "Geotech basics",
    "Health & safety",
    "Tenders",
  ],
  "HR / People": [
    "Talent acquisition",
    "Recruiting",
    "People operations",
    "Employee relations",
    "HRIS",
    "Compensation & benefits",
    "Performance management",
    "Onboarding",
    "Learning & development",
    "Workforce planning",
    "Employer branding",
    "Labor law basics",
    "Organizational development",
    "HR analytics",
    "Employee experience",
    "Diversity & inclusion",
  ],
  Marketing: [
    "Brand strategy",
    "Campaign management",
    "Content marketing",
    "SEO",
    "SEM / PPC",
    "Social media",
    "Email marketing",
    "Marketing analytics",
    "Go-to-market",
    "Product marketing",
    "Lifecycle marketing",
    "Marketing ops",
    "CRM",
    "A/B testing",
    "Copywriting",
    "Demand generation",
  ],
  Construction: [
    "Site management",
    "Construction planning",
    "Safety management",
    "Quantity surveying",
    "Contractor coordination",
    "Building codes",
    "Quality control",
    "Scheduling",
    "Cost control",
    "Blueprints reading",
    "Heavy equipment coordination",
    "Permit management",
    "Subcontractor management",
    "Punch lists",
  ],
  Infrastructure: [
    "Civil infrastructure",
    "Utilities coordination",
    "Roadworks",
    "Water systems",
    "Energy infrastructure",
    "Project delivery",
    "GIS",
    "Asset management",
    "Public works",
    "Environmental compliance",
    "Surveying",
    "Infrastructure design",
  ],
  "Building Supervision": [
    "Site supervision",
    "Inspection",
    "Building codes",
    "Safety compliance",
    "Quality assurance",
    "Progress reporting",
    "Contractor oversight",
    "Structural inspection",
    "Finishes inspection",
    "Documentation",
    "Handover management",
    "Defect management",
  ],
};

export const SKILL_FIELDS = Object.keys(SKILLS_BY_FIELD);
