export const SKILLS_BY_FIELD: Record<string, string[]> = {
  "Full Stack": [
    "React",
    "Node.js",
    "TypeScript",
    "PostgreSQL",
    "REST APIs",
    "Docker",
    "Next.js",
    "GraphQL",
  ],
  "Digital Project Manager": [
    "Agile",
    "Scrum",
    "Jira",
    "Stakeholder management",
    "Roadmapping",
    "Budget management",
    "Risk management",
  ],
  "Networking Engineer": [
    "TCP/IP",
    "Cisco",
    "Routing & Switching",
    "Firewalls",
    "VPN",
    "Network security",
    "SD-WAN",
  ],
  "Marketing Manager": [
    "Brand strategy",
    "Campaign management",
    "Content strategy",
    "Analytics",
    "Budget management",
    "Team leadership",
  ],
  "Hardware Engineer": [
    "Circuit design",
    "PCB layout",
    "Embedded systems",
    "Signal integrity",
    "Soldering",
    "Oscilloscope debugging",
  ],
  "PCB Design": [
    "Altium Designer",
    "KiCad",
    "Schematic capture",
    "Layout routing",
    "DFM",
    "Signal integrity",
  ],
  "QA Automation": [
    "Selenium",
    "Playwright",
    "Cypress",
    "CI/CD",
    "Test frameworks",
    "API testing",
    "Performance testing",
  ],
  "PPC Manager": [
    "Google Ads",
    "Meta Ads",
    "Campaign optimization",
    "A/B testing",
    "Budget management",
    "Analytics",
  ],
  "Social Media Manager": [
    "Content creation",
    "Community management",
    "Social analytics",
    "Paid social",
    "Influencer marketing",
  ],
  "Cyber Security": [
    "Penetration testing",
    "SIEM",
    "Incident response",
    "Network security",
    "Threat intelligence",
    "Compliance",
  ],
  DevOps: [
    "Kubernetes",
    "Docker",
    "CI/CD",
    "Terraform",
    "AWS/GCP/Azure",
    "Monitoring",
    "Linux administration",
  ],
  "Project Manager (Systems/Software)": [
    "Agile",
    "Scrum",
    "Technical roadmapping",
    "Cross-functional coordination",
    "Risk management",
  ],
  "Architect (Software)": [
    "System design",
    "Microservices",
    "Cloud architecture",
    "API design",
    "Scalability",
    "Technical leadership",
  ],
  "Chemical Engineer": [
    "Process design",
    "Chemical safety",
    "Reactor design",
    "Quality control",
    "Regulatory compliance",
  ],
  "Biochemistry Engineer": [
    "Lab techniques",
    "Protein analysis",
    "Fermentation",
    "Quality control",
    "Regulatory compliance",
  ],
  Technologist: [
    "Process optimization",
    "Quality assurance",
    "Lab equipment",
    "Documentation",
    "Regulatory standards",
  ],
  "Mechanical Engineer": [
    "CAD",
    "SolidWorks",
    "AutoCAD",
    "Manufacturing processes",
    "Materials science",
    "Prototyping",
  ],
  Pharma: [
    "GMP",
    "Regulatory affairs",
    "Clinical trials",
    "Quality assurance",
    "Validation",
    "Documentation",
  ],
  "Architecture (Building)": [
    "AutoCAD",
    "Revit",
    "Building codes",
    "Construction management",
    "Structural design",
  ],
  "Civil/Building Engineer": [
    "Structural analysis",
    "AutoCAD",
    "Site supervision",
    "Building codes",
    "Project management",
  ],
};

export const SKILL_FIELDS = Object.keys(SKILLS_BY_FIELD);
